[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#087F8C"
backgroundColor = "#F7FAF8"
secondaryBackgroundColor = "#E4EFEC"
textColor = "#102A43"
font = "sans serif"
